package dev.lumenlang.lumen.lsp.bootstrap;

import dev.lumenlang.lumen.api.LumenAPI;
import dev.lumenlang.lumen.api.LumenProvider;
import dev.lumenlang.lumen.api.annotations.Call;
import dev.lumenlang.lumen.api.annotations.Registration;
import dev.lumenlang.lumen.api.bus.Subscribe;
import dev.lumenlang.lumen.api.scanner.RegistrationScanner;
import org.jetbrains.annotations.NotNull;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.lang.reflect.Method;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * AOT friendly {@link RegistrationScanner.Backend}. Loads its class list from a
 * precomputed resource generated by {@link RegistrationDumper} at build time,
 * so no jar walking, classloader probing, or directory scanning is required at
 * runtime. Suitable for shipping inside a closed world WebAssembly image.
 */
public final class StaticRegistrationScannerBackend implements RegistrationScanner.Backend {

    private static final @NotNull Logger LOGGER = Logger.getLogger(StaticRegistrationScannerBackend.class.getName());
    private static final @NotNull String RESOURCE = "/lumen-defaults.txt";

    private final @NotNull LumenAPI api;
    private final @NotNull List<Class<?>> defaults;

    /**
     * Creates a backend that processes every class listed in the embedded
     * defaults resource.
     *
     * @param api the API surface passed to every {@link Call} method
     */
    public StaticRegistrationScannerBackend(@NotNull LumenAPI api) {
        this.api = api;
        this.defaults = loadDefaults();
    }

    /**
     * Processes the precompiled list of registration classes. The
     * {@code basePackage} argument is accepted to match the backend contract
     * and otherwise ignored.
     */
    @Override
    public void scan(@NotNull String basePackage) {
        Class<?>[] sorted = defaults.toArray(new Class<?>[0]);
        Arrays.sort(sorted, Comparator.comparingInt(c -> {
            Registration reg = c.getAnnotation(Registration.class);
            return reg != null ? reg.order() : 0;
        }));
        for (Class<?> clazz : sorted) {
            process(clazz);
        }
    }

    private void process(@NotNull Class<?> clazz) {
        try {
            Object instance = clazz.getDeclaredConstructor().newInstance();
            boolean hasSubscribers = false;
            for (Method method : clazz.getDeclaredMethods()) {
                if (method.isAnnotationPresent(Call.class)) {
                    Class<?>[] params = method.getParameterTypes();
                    if (params.length != 1 || !LumenAPI.class.isAssignableFrom(params[0])) {
                        LOGGER.warning("@Call method " + clazz.getName() + "#" + method.getName() + " must accept exactly one LumenAPI parameter");
                        continue;
                    }
                    method.setAccessible(true);
                    method.invoke(instance, api);
                }
                if (method.isAnnotationPresent(Subscribe.class)) {
                    hasSubscribers = true;
                }
            }
            if (hasSubscribers) {
                LumenProvider.bus().register(instance);
            }
        } catch (Exception e) {
            LOGGER.log(Level.SEVERE, "Failed to process registration class: " + clazz.getName(), e);
        }
    }

    private static @NotNull List<Class<?>> loadDefaults() {
        List<Class<?>> out = new ArrayList<>();
        try (InputStream stream = StaticRegistrationScannerBackend.class.getResourceAsStream(RESOURCE)) {
            if (stream == null) {
                LOGGER.severe("Missing resource " + RESOURCE + ", static registration backend will register nothing. Run the registrationDump Gradle task to regenerate it.");
                return out;
            }
            try (BufferedReader reader = new BufferedReader(new InputStreamReader(stream, StandardCharsets.UTF_8))) {
                String line;
                while ((line = reader.readLine()) != null) {
                    String trimmed = line.trim();
                    if (trimmed.isEmpty() || trimmed.startsWith("#")) continue;
                    try {
                        out.add(Class.forName(trimmed));
                    } catch (Throwable t) {
                        LOGGER.log(Level.WARNING, "Failed to load registration class " + trimmed, t);
                    }
                }
            }
        } catch (IOException e) {
            LOGGER.log(Level.SEVERE, "Failed to read " + RESOURCE, e);
        }
        return out;
    }
}
